#include <iostream>
using namespace std;

/* Project Euler #2:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

int main()
{
    int first, second, next, sum;
    first = 0;
    second = 1;
    next = first + second;
    sum = 0;
    while (next <= 4000000) {
        if (next % 2 == 0) {
            sum += next;
        }
        first = second;
        second = next;
        next = first + second;
    }
    // Answer: 4613732
    cout << "The sum of the even-valued terms in the Fib Seq: " << sum << endl;
    return 0;
}
