#include <stdio.h>

/* Project Euler #2:
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million,
 * find the sum of the even-valued terms. */
#define LIMIT 4000000

int main()
{
    int first = 0;
    int second = 1;
    int next = first + second;
    int sum = next;
    while (next <= LIMIT) {
        if (next % 2) {
            sum += next;
        }
        first = second;
        second = next;
        next = first + second;
    }
    // Answer: 4613732
    printf("Sum of all even-valued terms: %d\n", sum);
    return 0;
}
